/**
 * @author mscharf
 */

export interface UserInterface
{
    id:number;
    user:string;
    real_name:string;
    lang:string;
    ip_limit:string;
    Ustatus:number;
    mitglied_id:number;
    timestamp:string;
    user_email:string;
    timezone:string;
    google_email:string;
    skype:string;
    ical:string;
    ps_config:number;
    ps_article:number;
    ps_ebay:number;
    ps_stock:number;
    ps_customer:number;
    ps_order:number;
    ps_stats:number;
    ps_data:number;
    pc_config:number;
    pc_content:number;
    pc_newsletter:number;
    pc_layout:number;
    pc_dialog:number;
    pc_stats:number;
    pc_data:number;
    pc_blog:number;
    signature:null;
    color:string;
    eks:number;
    payments:number;
    accept_agb:number;
    plenty_api:number;
    image:string;
    del_order:number;
    del_article:number;
    del_record:number;
    plentystat:number;
    plentyconnect:number;
    webspace_access:number;
    access_control_list:string;
    plentymarkets_shipping_orderid:number;
    plentymarkets_shipping_article:number;
    plentymarkets_shipping_auto:number;
    plentymarkets_shipping_label:number;
    plentymarkets_shipping_config:number;
    storehouse_id:null;
    calendar:number;
    order_status:string;
    storehouse_repair_id:null;
    project:number;
    ticket:number;
    order:number;
    blog:number;
    lead:number;
    customer:number;
    user_total_vacation_days:number;
    user_role_id:null;
    salutation:string;
    calendar_pwd:null;
    data_lang:null;
    disabled:number;
    secure_login:number;
    plenty_user_scheduler:number;
    plenty_user_item:number;
    incoming_items:number;
    plenty_user_git_user:string;
    plenty_user_git_auth_type:string;
    plenty_user_git_pwd:string;
}
