name: plugin terra basic CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: npm run reinstall
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build and test
        run: |
          npm run build --if-present
          npm run test-headless
        env:
          CI: true
