# Name of the workflow
name: Bumb a new pull request when there is a new version of Terra Components

# Controls when the action will run. Triggers the workflow on push or pull request
on:
    schedule:
        # runs at 00:00 every day
        - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # Name of the job
    tc-latest:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@v2
            - uses: Bruce17/ghaction-package-latest-version@v1.1.0
              with:
                  package: '@plentymarkets/terra-components'
                  language: node
