# Name of the workflow
name: Comparison to master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Name of the job
  check-integrity:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Clean install of the node dependencies
      - name: Clean install
        run: npm ci

      # Runs the set of integrity checks concurrently
      - name: Run checks
        run: |
          npm run lint
          npm run build
  
  automerge:
    runs-on: ubuntu-latest
    name: Merge pull request of the dependabot
    needs: [check-integrity]
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - name: Merge dependabot
        uses: actions/github-script@v2
        with:
          script: |
             github.pullRequest.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
              })
          github-token: ${{github.token}}
